### ISSUE TITLE
Feature Request:  Configuration option for display name and state

### ISSUE THREAD

**Issue by manonstreet** [rodpayne/home-assistant_person_location#17] opened 2024-04-22 14:14 UTC
The sensor.name_location entity currently has a display name of "Name is at Location", with a state of either: Home, Away, Just Arrived, or Just Left.

In my setup, I am using the provided location entities in a glance card and the display name is too long, and the specific zone where the person is located is not visible.  I still prefer to use this integration's location entity however for the geocoded information visible when clicking on the entity, as well as the transitioning from home state status.

It would be great if this integration could add a configuration option for the sensor information to mimic a person entity (with the added benefit of Just Arrived and Just Left).  Specifically, when this proposed setting is turned on, person_name is used as the entity display name and reported_state is used as the state value.

**Comment by rodpayne** [comment] 2024-04-23 13:13
I am thinking of having something like a configuration parameter `friendly_name_template`:

`"{{ person_name }} ({{ trigger_friendly_name }}) {{ location }}"` for the default, original format.

`"{{ person_name }}"` or `{{ person_name }} {{ location }}` for an abbreviated format.

Example variables:

`person_name` - the person's name from the configuration.

`trigger_friendly_name` - the `friendly_name` of the device tracker that triggered the update.

`location` - the zone or locality that was determined, like `is Away`, `is at Walmart`, `is in Peoria`.

**What do you think?  Would that meet the case that you are looking for?  What other variables would someone want to be available?**

**Comment by manonstreet** [comment] 2024-04-23 13:39
For the friendly name, this would work great for me and I think it's flexible enough that it could be helpful for others as well.

I'm also keen to be able to have the location entity have its state value reflect the zone name, as opposed to simply "Away" (matching the reported_state).  Can you consider also adding a boolean configuration parameter?  Maybe something like `show_zone_name_when_away` with a default of `False`?

With these 2 configuration parameters combined, it would allow me to mimic a person entity in a glance card.

Thanks!

**Comment by rodpayne** [comment] 2024-04-23 18:25
My understanding of a person entity is that its state is either `Home`, `Away`, or a zone name.  Just to clarify, are you looking to replace the person location state value of `Away` with the zone name if it is in a zone?  Or, do you want to show only state values of `Home`, `Away`, or a zone name, and eliminate the `Just Left`, `Just Arrived`, and `Extended Away` possibilities? 

I think that I would choose to use the first option myself.  As far as mimicking how the person entity would show it, the `Just Left`, `Just Arrived`, and `Extended Away` states would just look like other zone names.  

The latter option would essentially be turning off the "Make presence detection not so binary" feature.

**Comment by manonstreet** [comment] 2024-04-23 19:28
> My understanding of a person entity is that its state is either `Home`, `Away`, or a zone name. Just to clarify, are you looking to replace the person location state value of `Away` with the zone name if it is in a zone? Or, do you want to show only state values of `Home`, `Away`, or a zone name, and eliminate the `Just Left`, `Just Arrived`, and `Extended Away` possibilities?
> 
> I think that I would choose to use the first option myself. 

Indeed, I mean the first option.

**Comment by manonstreet** [comment] 2024-05-07 14:34
FYI - I no longer need this feature.  I am now using multiple-entity-row from hacs to show various information (battery, driving distance, zone) that meets my needs.  In this setup I can access various name and zone state information across multiple entities in a single row without requiring a single entity (ie the location sensor) to have all of the data formatted in a specific manner.

**Comment by manonstreet** [comment] 2024-05-31 14:04
Thanks @rodpayne 🙏

**Comment by rodpayne** [comment] 2024-05-31 15:39
If you have a chance, please test out pre-release 2024.05.30.  This first commit is for the `friendly_name` part of it, Next, I'll work on showing the zone in `state`.

**Comment by manonstreet** [comment] 2024-05-31 23:44
I receive this error during startup (and after):

```
Logger: homeassistant.core
Source: core.py:2758
First occurred: 7:40:09 PM (3 occurrences)
Last logged: 7:40:35 PM

Error executing service: <ServiceCall person_location.process_trigger (c:01HZ8GCTCYT0F5Y327FCQW4V32): entity_id=person.<name1_redacted>, from_state=unknown, to_state=not_home>
Error executing service: <ServiceCall person_location.process_trigger (c:01HZ8GCTD18Y5R3PK1D260QXY6): entity_id=person.<name2_redacted>, from_state=unknown, to_state=not_home>
Error executing service: <ServiceCall person_location.process_trigger (c:01HZ8GDJY4F5F5E6NPG7YX5B26): entity_id=person.<name2_redacted>, from_state=unknown, to_state=not_home>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2758, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2786, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/person_location/process_trigger.py", line 473, in handle_process_trigger
    friendly_name_location,
    ^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'friendly_name_location' where it is not associated with a value
```

**Comment by rodpayne** [comment] 2024-06-01 00:40
Should be fixed in pre-release 2024.05.31. This was happening when following a `person` entity.

**Comment by manonstreet** [comment] 2024-06-01 19:45
Looks good. Since the friendly_name only updates on change of zone, to fully test, I had to restart HA again.  After that, my template is being rendered as configured.  

The only suggestion I have is to update the friendly_name according to the template when the integration is reconfigured and/or reloaded so that the user can get immediate feedback that it's working.

**Comment by manonstreet** [comment] 2024-06-07 00:13
I upgraded to 2024.06.03, and also just upgraded my HA to 2024.6.0.  I receive the following error on start

```
Error setting up entry Person Locations for person_location
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/person_location/__init__.py", line 243, in async_setup_entry
    return await hass.data[DOMAIN][DATA_ASYNC_SETUP_ENTRY](hass, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/person_location/__init__.py", line 93, in _async_setup_entry
    entry.options["friendly_name_template"] != pli.configuration["friendly_name_template"]
                                               ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'friendly_name_template'
```

**Comment by manonstreet** [comment] 2024-06-07 21:01
Updated to version 2024.06.07 - same error on HA start.

**Comment by rodpayne** [comment] 2024-06-08 14:53
I was able to reproduce the startup error in v2024.06.07 on HA Core 2024.5.5. It looks like v2024.06.08 takes care of it.

I took friendly_name_template out of the config in core.config_entries and confirmed that the problem was in trying to decide if there was a change in friendly_name_template (to refresh the friendly_name of the output sensors), but before friendly_name_template was in the configuration.

**Comment by manonstreet** [comment] 2024-06-08 16:10
I just tested and it appears everything is work great:

1. No more startup errors.  
2. Friendly template rendered correctly
3. Friendly template immediately rendered when re-configuring the integration
4. The sensor state is reflecting the zone name when the person is away (when enabling the setting)

Thank you for these updates!  I think this FR can be closed.

**Comment by rodpayne** [comment] 2024-06-09 12:33
Excellent. Thank you for the ideas and for testing.

**Closed as completed by rodpayne** 2024-06-09 12:33 UTC
Labels: enhancement
